import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className="antialiased bg-white dark:bg-neutral-950">
          <ThemeProvider attribute="class" enableSystem>
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
